$ErrorActionPreference = "Stop"
Set-Location "D:\HermesWorker\GDrive\Project_V7_Rotation\alpha_pit_engine_crypto_20260519_remote"
$env:ALPHAFACTORY_CRYPTO_DATA_ROOT = "D:\HermesWorker\GDrive\AlphaFactory_CryptoData"
$env:A7AL_BASE_PANEL_ROOT = "D:\HermesWorker\GDrive\AlphaFactory_CryptoData\gold\features\binance_universe498_replay_1h_v2_20260527"
$env:A7FF8_STAGE = "A7FF-19S01"
$env:A7FF8_FILE_PREFIX = "a7ff19s01"
$env:A7FF8_RUNTIME = "D:\HermesWorker\GDrive\Project_V7_Rotation\alpha_pit_engine_crypto_20260519_remote\runtime\a7ff19_company_numeric_confirmation_shard_01"
$env:A7FF8_REPORT = "D:\HermesWorker\GDrive\Project_V7_Rotation\alpha_pit_engine_crypto_20260519_remote\reports\CRYPTO_A7FF19S01_COMPANY_NUMERIC_CONFIRMATION_20260530.md"
$env:A7FF8_QUEUE_PATH = "D:\HermesWorker\GDrive\Project_V7_Rotation\alpha_pit_engine_crypto_20260519_remote\runtime\a7ff19_external_selector_confirmation_contract\a7ff19_execution_queue.csv"
$env:A7FF8_QUEUE_OFFSET = "28"
$env:A7FF8_QUEUE_LIMIT = "28"
$env:A7FF8_MATERIALIZE_CAP = "28"
$env:A7FF8_FAST_NUMERIC_CAP = "28"
$env:A7FF8_PORTFOLIO_CAP = "128"
& "D:\HermesWorker\venvs\phase3z33\Scripts\python.exe" "scripts\crypto_a7ff8_expanded_numeric_probe.py"
